---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-api
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./.deploy/helm/backend-api
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: medicine-prescriber-prototype
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: backend-api
  targetNamespace: backend
  valuesFrom:
  - kind: Secret
    name: values-backend-api

