---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./.deploy/helm/frontend-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: medicine-prescriber-prototype
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: frontend-app
  targetNamespace: frontend
  valuesFrom:
  - kind: Secret
    name: values-frontend-app

