backendAPIURL: "http://localhost:8080"
authoriseURL: "https://<TENANT_DOMAIN>/authorize"
redirectURL: "http://localhost:9090/auth.html"
audience: "<AUDIENCE>"
clientID: "<CLIENT ID>"
symptomsSeparator: "|"
scopes:
  - "read:user_profile"
  - "save:user_profile"
  - "read:subjective_symptoms"
  - "read:associated_symptoms"
  - "read:investigations"
  - "read:gender"
  - "read:age_groups"
  - "predict:provisional_diagnosis"
  - "read:advises"
  - "openid"
  - "profile"
  - "email"
