{{- if .Values.letsencrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "letsencrypt.issuerName" . }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: {{ include "letsencrypt.server" . }}
    privateKeySecretRef:
      name: {{ include "letsencrypt.issuerName" . }}
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                nodeSelector:
                  "kubernetes.io/os": linux
                  "kubernetes.io/arch": "arm64"
                tolerations:
                  - key: "kubernetes.io/arch"
                    value: "arm64"
{{- end -}}
