{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" (include "backend-api.fullname" .) "file")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-api.fullname" . }}-file
type: Opaque
data:
{{ (.Files.Glob "data/*").AsSecrets | indent 2 }}
{{- end -}}
