{{- if .Values.letsencrypt.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: {{ include "letsencrypt.server" }}
    privateKeySecretRef:
      name: letsencrypt-app
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                nodeSelector:
                  "kubernetes.io/os": linux
{{- end -}}
