apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend-app.fullname" . }}
type: Opaque
stringData:
  config.yaml: |
    backendAPIURL: "{{ .Values.config.backendAPIURL }}"
    authoriseURL: "{{ .Values.config.authoriseURL }}"
    redirectURL: "{{ .Values.config.redirectURL }}"
    audience: "{{ .Values.config.audience }}"
    clientID: "{{ .Values.config.clientID }}"
    {{- with .Values.config.scopes }}
    scopes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
