name: build_backend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/api/requirements.txt -r ./backend/api/requirements_dev.txt
      - name: Lint with pylint
        run: |
          pylint --errors-only ./backend/api
      - name: Test with pytest
        run: |
          pytest -v --cov=backend/api --cov-report=xml:coverage.xml
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
