name: build_frontend

on: 
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ["self-hosted", "Linux", "ARM64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
