name: publish

on:
  pull_request:
    branches:
      - main
    # types:
    #   - closed

jobs:
  docker:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/1011289596614/locations/global/workloadIdentityPools/github-ci-pool/providers/github-ci-provider"
          service_account: "github-ci-sa"
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend/api
          push: true
          tags: asia.gcr.io/ai-hospital-services-prototype/backend-api:test
