name: publish_machine_learning_training

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/1011289596614/locations/global/workloadIdentityPools/prototype-github-ci-pool/providers/prototype-github-ci-oidc"
          service_account: "prototype-github-ci-sa@ai-hospital-services-prototype.iam.gserviceaccount.com"
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: asia.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./machine_learning/pipelines/training
          push: true
          tags: asia.gcr.io/ai-hospital-services-prototype/machine_learning_training:tensorflow_dnn
